<2020-04-09 Thu>
Timestamps must be used in org mode only huh? No problem
* PPA problem gone! 
Very important entry right here in the sense that I'm recalling a 5month long problem and the steps taken to solve it.
** For months I had an "Error BrokenCount >0" on the right hand side of my Ubuntu box.
I knew to click on properties > Other Software, but as I looked at those packages I didn't realize the Ubuntu eLisp was the propblem.
You can also get to that screen with the cmd gksu software-properties-gtk
After clicking to remove eLisp, I then typed
#+begin_src
 sudo apt-get update && sudo apt-get install -f && sudo apt-get update
#+end_src
Then restarted the computer and the error message was gone! 
Then my virtual box started working again, for some reason after updated vbox to 6.1 it stopped working b/c of this unmet dependencies prob.
The catastrophe I was faced with today, though small, was a great reminder about backups. I had *just* created a Lubuntu vm
Then I could not access/turn it on b/c of this silly uid error, which in the end, didn't relate at all to the solution I found with the ppa fix.
Something in the back of my mind was nagging at me to fix ppa first, and not worry about the newly created vbox issue that mysteriously came about right after updating! 
<2020-04-10 Fri>
** twitter take aways
*** Jerry Jeudy good WR from Alabama but wears #4?
*** Utah CB says he's the smartest CB in the draft Jaylon Johnson
*** Stephon Gilmore while at South Carolina qb'ed a pass to Alshon Jeffrey(who looked so fat and slow)
*** made an awful joke about Demarcus Robinsons horrible hair (Drob from the Gators) was he #11 back then?
** podcast points
*** Very few americans have been tested 0.01% 
* Productive Saturday morning! 
well, i hope so! I did follow one step in my less-coffee resolution: drank 8 cups of tea
** podcast points
*** TWiV is really into testing! Amazing that Singapore has a unique solution to dengue Mosquitos:  
Wolbachia carrying Aedes aegypti mosquitos
*** Aedes is a genus
*** epidemiology is the study of how disease spreads! Why does Cuba do so well in Medicine?
*** So basically this male mosquito has a bacteria (Wolbachia) that ma kes the eggs a female hatches never hatch
*** other mosquito types (genus and species?) are crazy but I'll type them here: anopheles coluzzii, culex quinquefasciatus
*** From Dale Carnegie's book How to Stop worrying: prideful trees that don't bend under the snow eventually break
*** bend not break phrase is always in sports! He also told the story of thoughts manifesting feelings
*** For ex. if you think about being weak, you feel week. About being stressed, you are stressed.
*** my solution is find quotes that create feelings for ex. Ralph Emerson on success, then ask myself have I done these? Yes!
*** I should create a meditation resource to focus on to control my thoughts to be what I want them to be, maybe use quotes?
*** Prisoners in Sing-Sing seem just as happy as anyone in the outside world
* to laugh often and love much; to win the respect of intelligent people & the affection of children; to earn the approbation of honest critics and endure the betrayal of false friends; to appreciate beauty.
<2020-04-13 Mon>
* Heavy Econ Morning, then work work work 
** The Falcon and the Snowman
*** TODO watch Aldrich Ames 1998 movie, also about spying also starring Tim Hutton!
*** main char paroled in 1998, sean penn then hired him as a personal assistant??!?!
*** instead of RTX the company in real life was TRW
**** this company created a few interesting spacecrafts including Pioneer 1 (failure) and 10 (successful to Jupiter)
**** acquired by NOC in 2002 but it sounds like the pieced out parts of TRW to become Pacific Semiconductors, Aerospace, etc
**** interesting, TRW veterans were instrumental in founding SpaceX
*** the part of the movie about Whitlam lead me down an interesting rabbit hole 
**** according to wikipedia: Kerr replace Whitelam as Australia's prime minister after support/money from CIA
**** the main char claims he read a CIA correspondence saying "our man Kerr" but even Whitlam sad Kerr didn't need cia help
**** Also Whitlam said Jimmy Carter sent an ambassador specially to Sydney to reassure that US won't be involved in Aussie democracy
**** 
** Fed research morning
*** really like investopedia's structure with "key takeways" and "bottom line"
*** weapon of mass protection lol
*** key features to enforce a certain monetary policy: omo, qe,  

