*  Thoughts manifest feelings
** Ralph Waldo Emerson
*** to be yourself in a world that is constantly trying to make you something else is the greatest accomplishment
*** it is the blessings of old friends that you can afford to be stupid with them
*** I cannot remember the books I've read any more than the meals I have eaten; even so they have made me
*** live in the sunshine, swim in the sea, drink the wild air
*** The purpose of life is not to be happy. It is to be useful...
*** when it is dark enough, you can see the stars 
**** to me this is all about dark times in life! When you are going through darkest times, your loved ones are your stars! They are easy to see!
*** What you do speaks so loudly that I cannot hear what you say
*** Is it bad, then, to be misunderstood? Pythagoras was misunderstood, and socrates, and jesus, and luther, and copernicus and galileo and newton.."
*** make your own bible. select and collect all the words and sentences that in all your readings have been to you like the blast of a trumpet
*** it is not the length of life, but the depth
**** that's why to me, my most important mission is to get my children to a good age, 1st milestone I imagine is 18, then 25, then 35 and so on! always remembering to live deeply!
***  

** Edgar Allen Poe

** Funny
*** 99 lil bugs in the code, 99 lil bugs, take one down, patch it around, 117 lil bugs int he code
